[package]
name = "web-pi"
version = "0.1.0"
edition = "2021"

[dependencies]
wry = "0.45"
winit = "0.30"
dpi = "0.1"
gtk = "0.18"

# [target.aarch64-unknown-linux-gnu]
# linker = "/usr/bin/aarch64-linux-gnu-gcc"
