[target.aarch64-unknown-linux-gnu]
pre-build = [
  "export PKG_CONFIG_PATH=/usr/aarch64-linux-gnu/lib/",
  "dpkg --add-architecture arm64 && apt-get update && apt-get install -y libjavascriptcoregtk-4.0-18 libsoup2.4 && apt-get install -y libwebkit2gtk-4.0-dev build-essential wget libssl-dev librsvg2-dev libgtk-3-dev libgdk-pixbuf2.0-dev"
]
