[target.aarch64-unknown-linux-gnu]
# linker = "aarch64-linux-gnu-gcc"
# linker = "distcc"
linker = "/usr/aarch64-linux-gnu/bin/ld"
# linker = "clang"
# rustflags = ["-C", "link-arg=-fuse-ld=/usr/aarch64-linux-gnu/bin/ld"]
